# Generated by Django 4.1 on 2022-11-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_field_plant_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='field',
        ),
    ]
