# Generated by Django 4.1 on 2022-11-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_botany_plant_botany_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='botany_branch',
            new_name='botany',
        ),
    ]
