# Generated by Django 4.1 on 2022-11-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_remove_plant_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Field',
        ),
    ]
